### ISSUE TITLE
Option to limit mobile data usage by reducing audio & image quality

### ISSUE THREAD

**Issue by astarq** [stonega/tsacdop#10]
This would make sense as most people listen to podcasts while commuting and on the move, and it would also mean podcasts load quicker. 

Side note: an option to prevent the loading of images would also be greatly appreciated, as they seem to consume a lot of data

Thanks for creating an open source app, I couldn't believe my eyes when I found it on Izzyondroid

**Comment by stonega** [comment]
Hi，thanks for your feedback!
I‘m not sure if it is possible to reduce the quality of audio, because user get audio directly from podcast host server. The only solution is to download it when wifi available.
About the image, do you the images in show notes? The avatar was downloaded when you subscribe the podcast, and stored locally.

**Comment by astarq** [comment]
Hi, thanks for your reply

Thanks for explaining, guess I'll just have to be THAT friend who always needs the wifi passcode.. 🤗

Sorry you're right, avatars are the only images (that I've noticed). I only mentioned that because after adding all my podcasts the data usage seemed quite high. Then again, as the images are stored locally it doesn't really matter.
7 Aug 2020, 15:35 by notifications@github.com:

**Comment by stonega** [comment]
@astarq  There are actually some images in some episode show notes, you remind me that I need to add a option to check if load image in show note.
